<?php

namespace Tabula17\Orbitalis\Odf\Co\Components;
/**
 * Represents a job with attributes including identifiers, directories, data, actions, and timestamps.
 * Provides functionality to convert the job's properties into an array format.
 *
 * Properties include:
 * - id: Unique identifier for the job.
 * - template: The template associated with the job.
 * - workingDir: The working directory for the job's execution.
 * - outputDir: Directory where the job's output is stored.
 * - outputName: Name of the output generated by the job.
 * - data: Input data required for the job.
 * - success: Status of the job's success, null if the status is unknown.
 * - actions: List of actions taken during the job's execution.
 * - createdAt: Timestamp indicating when the job was created.
 * - updatedAt: Timestamp indicating when the job was last updated.
 * - completedAt: Timestamp indicating when the job was completed.
 * - errorMessage: Error message if the job encountered an issue.
 * - parameters: Optional parameters passed to the job.
 * - results: Output/results produced by the job.
 */
final class Job
{
    public function __construct(
        public string          $id,
        public readonly string $template,
        public readonly string $workingDir,
        public readonly string $outputDir,
        public readonly string $outputName,
        public readonly array  $data,
        public ?bool           $success = null,
        public readonly array  $actions = [],
        public ?string         $createdAt = null,
        public ?string         $updatedAt = null,
        public ?string         $completedAt = null,
        public ?string         $errorMessage = null,
        public ?array          $parameters = null,
        public ?array          $results = null
    )
    {
    }

    public function __toArray(): array
    {
        return get_object_vars($this);
    }
}